import assert from 'node:assert/strict'
import test from 'node:test'
import { EXPECTED_SCHEMA, READ_ONLY_SCHEMA_SQL, buildD1SchemaCommand, runD1SchemaCheck, validateD1SchemaResults } from './staging-d1-schema-check.mjs'
function result(results){return{success:true,results,meta:{rows_read:results.length,rows_written:0}}}
function validPayload(){return[result(EXPECTED_SCHEMA.tables.map(name=>({name,type:'table'}))),result(EXPECTED_SCHEMA.reportColumns.map((name,cid)=>({cid,name,type:'TEXT'}))),result(EXPECTED_SCHEMA.moderationColumns.map((name,cid)=>({cid,name,type:'TEXT'}))),result(EXPECTED_SCHEMA.indexes.map(name=>({name})))]}
test('schema SQL is read-only and inspects the 0001-0004 surface',()=>{assert.match(READ_ONLY_SCHEMA_SQL,/sqlite_master/);assert.match(READ_ONLY_SCHEMA_SQL,/PRAGMA table_info\(reports\)/);assert.match(READ_ONLY_SCHEMA_SQL,/PRAGMA table_info\(report_moderation_events\)/);assert.doesNotMatch(READ_ONLY_SCHEMA_SQL,/\b(?:INSERT|UPDATE|DELETE|ALTER|DROP|CREATE|REPLACE)\b/i)})
test('schema command is pinned to staging, remote, JSON and Wrangler 4.125.0',()=>{const command=buildD1SchemaCommand();assert.equal(command.command,'npx');assert.ok(command.args.includes('--package=wrangler@4.125.0'));assert.ok(command.args.includes('barrio24-reports-staging'));assert.ok(command.args.includes('--remote'));assert.ok(command.args.includes('--json'));assert.ok(command.args.includes('api/wrangler.toml'));assert.ok(command.args.includes(READ_ONLY_SCHEMA_SQL));assert.ok(!command.args.includes('apply'))})
test('schema validator accepts the exact expected tables, columns and indexes',()=>{const validated=validateD1SchemaResults(validPayload());assert.deepEqual(validated.tables,[...EXPECTED_SCHEMA.tables].sort());assert.ok(validated.reportColumns.includes('last_moderation_event_id'));assert.ok(validated.moderationColumns.includes('idempotency_key'));assert.ok(validated.indexes.includes('reports_status_received_event_idx'))})
test('schema validator rejects missing columns, indexes or writes',()=>{const missingColumn=validPayload();missingColumn[1].results=missingColumn[1].results.filter(({name})=>name!=='last_moderation_event_id');assert.throws(()=>validateD1SchemaResults(missingColumn),/reports columns mismatch/);const missingIndex=validPayload();missingIndex[3].results=missingIndex[3].results.filter(({name})=>name!=='report_moderation_events_retention_idx');assert.throws(()=>validateD1SchemaResults(missingIndex),/D1 indexes mismatch/);const wroteRows=validPayload();wroteRows[0].meta.rows_written=1;assert.throws(()=>validateD1SchemaResults(wroteRows),/unexpectedly wrote 1 rows/)})
test('schema validator rejects failed or malformed Wrangler output',()=>{assert.throws(()=>validateD1SchemaResults([]),/expected 4 result sets/);const failed=validPayload();failed[2].success=false;assert.throws(()=>validateD1SchemaResults(failed),/result 3 was not successful/)})
test('runD1SchemaCheck generates config before executing and validates JSON output',async()=>{const calls=[];const validated=await runD1SchemaCheck({generateConfig:async()=>{calls.push('config')},commandRunner:async(command,args)=>{calls.push({command,args});return JSON.stringify(validPayload())}});assert.equal(calls[0],'config');assert.equal(calls[1].command,'npx');assert.deepEqual(validated.tables,[...EXPECTED_SCHEMA.tables].sort())})
test('runD1SchemaCheck fails closed on non-JSON Wrangler output',async()=>{await assert.rejects(runD1SchemaCheck({generateConfig:async()=>{},commandRunner:async()=> 'not json'}),/did not return valid JSON/)})
