import assert from 'node:assert/strict'
import test from 'node:test'

import { EXPECTED_STAGING } from './staging-constants.mjs'
import { buildPublicAbuseCases, runPublicAbuseProbe } from './staging-public-abuse-probe.mjs'

const IDS=['11111111-1111-4111-8111-111111111111','22222222-2222-4222-8222-222222222222','33333333-3333-4333-8333-333333333333','44444444-4444-4444-8444-444444444444','55555555-5555-4555-8555-555555555555','66666666-6666-4666-8666-666666666666']; const OBSERVED_AT='2026-08-24T05:00:00.000Z'
function response(status,error){return new Response(JSON.stringify({error}),{status,headers:{'content-type':'application/json','access-control-allow-origin':EXPECTED_STAGING.pagesOrigin}})}
function deterministicCases(){let index=0;return buildPublicAbuseCases({idFactory:()=>IDS[index++],observedAt:OBSERVED_AT})}

test('abuse cases cover privacy and payload validation without a valid report',()=>{const cases=deterministicCases();assert.deepEqual(cases.map(({name})=>name),['invalid-json','exact-coordinate-fields-rejected','over-precise-location-cell-rejected','unknown-category-rejected','invalid-observed-at-rejected','oversized-payload-rejected']);const coordinates=JSON.parse(cases[1].body);assert.equal(coordinates.latitude,-12.0464);assert.equal(coordinates.longitude,-77.0428);assert.equal(JSON.parse(cases[2].body).location_cell,'-12.046,-77.043');assert.ok(Buffer.byteLength(cases[5].body,'utf8')>2048);assert.ok(cases.every(({expectedStatus})=>expectedStatus>=400))})
test('abuse probe refuses any non-staging Worker URL before fetching',async()=>{let called=false;await assert.rejects(runPublicAbuseProbe({fetchImpl:async()=>{called=true;throw new Error('must not fetch')},baseUrl:'https://barrio24.example.com',cases:deterministicCases()}),/authorized staging Worker/);assert.equal(called,false)})
test('abuse probe refuses any non-staging Pages origin before fetching',async()=>{let called=false;await assert.rejects(runPublicAbuseProbe({fetchImpl:async()=>{called=true;throw new Error('must not fetch')},pagesOrigin:'https://example.com',cases:deterministicCases()}),/non-staging Pages origin/);assert.equal(called,false)})
test('abuse probe sends only public report requests and accepts the expected rejection contracts',async()=>{const cases=deterministicCases();const calls=[];let clientIndex=0;const fetchImpl=async(url,init={})=>{const testCase=cases[calls.length];calls.push({url,init});return response(testCase.expectedStatus,testCase.expectedError)};const result=await runPublicAbuseProbe({fetchImpl,cases,clientIdFactory:()=>IDS[clientIndex++]});assert.equal(result.results.length,cases.length);assert.equal(calls.length,cases.length);assert.ok(calls.every(({url})=>url===`${EXPECTED_STAGING.workerUrl}/v1/reports`));assert.ok(calls.every(({url})=>!url.includes('/v1/ops/')));assert.ok(calls.every(({init})=>init.method==='POST'));assert.ok(calls.every(({init})=>init.headers.Origin===EXPECTED_STAGING.pagesOrigin));assert.equal(new Set(calls.map(({init})=>init.headers['X-Client-Id'])).size,cases.length)})
test('abuse probe fails closed if an invalid payload is accepted',async()=>{const cases=deterministicCases().slice(0,1);await assert.rejects(runPublicAbuseProbe({cases,fetchImpl:async()=>new Response(JSON.stringify({event_id:IDS[0],status:'unverified'}),{status:202,headers:{'access-control-allow-origin':EXPECTED_STAGING.pagesOrigin}})}),/expected HTTP 400, received 202/)})
test('abuse probe fails closed if CORS is missing on a rejection',async()=>{const cases=deterministicCases().slice(0,1);await assert.rejects(runPublicAbuseProbe({cases,fetchImpl:async()=>new Response(JSON.stringify({error:'invalid_json'}),{status:400,headers:{'content-type':'application/json'}})}),/staging origin missing/)})
