import assert from 'node:assert/strict'
import test from 'node:test'
import { loadEvidenceDirectory, parseEvidenceSummaryArgs, summarizeEvidence } from './staging-evidence-summary.mjs'
const SHA='a'.repeat(40),OTHER_SHA='b'.repeat(40)
function evidence(kind,overrides={}){return{kind,candidateSha:SHA,completedAt:'2026-08-24T12:00:00.000Z',status:'PASS',result:{},...overrides}}
test('summary args require candidate SHA and reject unsafe directories',()=>{assert.deepEqual(parseEvidenceSummaryArgs([`--expected-sha=${SHA}`]),{expectedSha:SHA,level:'p0',directory:'artifacts/staging-readiness'});assert.equal(parseEvidenceSummaryArgs([`--expected-sha=${SHA}`,'--level=p1']).level,'p1');assert.throws(()=>parseEvidenceSummaryArgs([]),/required/);assert.throws(()=>parseEvidenceSummaryArgs([`--expected-sha=${SHA}`,'--directory=../escape']),/safe relative path/)})
test('P0 summary is COMPLETE only when every automated P0 evidence kind matches the same SHA',()=>{const summary=summarizeEvidence([evidence('barrio24-staging-readonly-readiness'),evidence('d1-schema-readonly'),evidence('public-smoke'),evidence('public-abuse')],{expectedSha:SHA,level:'p0'});assert.equal(summary.automatedStatus,'COMPLETE');assert.deepEqual(summary.missing,[]);assert.equal(summary.selected.length,4)})
test('summary rejects mismatched SHA and non-PASS evidence instead of counting it',()=>{const summary=summarizeEvidence([evidence('barrio24-staging-readonly-readiness'),evidence('d1-schema-readonly',{candidateSha:OTHER_SHA}),evidence('public-smoke',{status:'FAIL'}),evidence('public-abuse')],{expectedSha:SHA,level:'p0'});assert.equal(summary.automatedStatus,'INCOMPLETE');assert.deepEqual(summary.missing.sort(),['d1-schema-readonly','public-smoke']);assert.equal(summary.rejected.length,2)})
test('P1 additionally requires both bounded load profiles',()=>{const base=[evidence('barrio24-staging-readonly-readiness'),evidence('d1-schema-readonly'),evidence('public-smoke'),evidence('public-abuse')];assert.deepEqual(summarizeEvidence(base,{expectedSha:SHA,level:'p1'}).missing,['controlled-load-rate-limit','controlled-load-burst']);const complete=summarizeEvidence([...base,evidence('controlled-load-rate-limit'),evidence('controlled-load-burst')],{expectedSha:SHA,level:'p1'});assert.equal(complete.automatedStatus,'COMPLETE')})
test('summary selects the newest valid artifact of a required kind',()=>{const summary=summarizeEvidence([evidence('barrio24-staging-readonly-readiness',{completedAt:'2026-08-24T10:00:00.000Z'}),evidence('barrio24-staging-readonly-readiness',{completedAt:'2026-08-24T13:00:00.000Z'}),evidence('d1-schema-readonly'),evidence('public-smoke'),evidence('public-abuse')],{expectedSha:SHA,level:'p0'});assert.equal(summary.selected.find(({kind})=>kind==='barrio24-staging-readonly-readiness').completedAt,'2026-08-24T13:00:00.000Z')})
test('loadEvidenceDirectory tolerates malformed JSON as rejected evidence input',async()=>{const items=await loadEvidenceDirectory('evidence',{list:async()=>['good.json','bad.json','ignore.txt'],read:async(filePath)=>filePath.endsWith('good.json')?JSON.stringify(evidence('public-smoke')):'{bad'});assert.equal(items.length,2);assert.ok(items.some(({kind})=>kind==='public-smoke'));assert.ok(items.some(({status})=>status==='INVALID'))})
test('loadEvidenceDirectory treats a missing evidence directory as an empty set',async()=>{const missing=Object.assign(new Error('missing'),{code:'ENOENT'});const items=await loadEvidenceDirectory('missing',{list:async()=>{throw missing}});assert.deepEqual(items,[])})
