import assert from 'node:assert/strict'
import test from 'node:test'
import { buildReadonlyReadinessSteps, runCommand, runReadonlyReadiness, writeReadinessEvidence } from './staging-readonly-readiness.mjs'
const SHA='a'.repeat(40)
function successfulOutcome(stdout=''){return{exitCode:0,durationMs:10,stdout,stderr:'',timedOut:false,outputLimitExceeded:false,terminationReason:null}}
function successfulPreflightOutput(step){if(step.id==='git-head-sha')return`${SHA}\n`;if(step.id==='git-branch')return'fix/rapid-report-production-readiness\n';return''}
test('readonly readiness contains preflight gates followed by safe validation steps',()=>{const steps=buildReadonlyReadinessSteps({expectedSha:SHA});assert.deepEqual(steps.map(({id})=>id),['git-head-sha','git-branch','git-worktree-clean','repo-check','wrangler-dry-run','wrangler-startup','d1-migrations-list','d1-schema-readonly']);const rendered=steps.map(({command,args})=>`${command} ${args.join(' ')}`).join('\n');assert.doesNotMatch(rendered,/migrations\s+apply/);assert.doesNotMatch(rendered,/\bwrangler\s+deploy\b(?!\s+--dry-run)/);assert.doesNotMatch(rendered,/staging:public-smoke|controlled-load|public-abuse|\/v1\/ops\//);assert.ok(steps.every(({timeoutMs,maxOutputBytes})=>timeoutMs>0&&maxOutputBytes>0));assert.ok(steps.find(({id})=>id==='d1-schema-readonly').args.includes(`--expected-sha=${SHA}`))})
test('readonly readiness records exact repository identity when every command succeeds',async()=>{const steps=buildReadonlyReadinessSteps({expectedSha:SHA}).slice(0,4);let tick=0;const evidence=await runReadonlyReadiness({steps,commandRunner:async(step)=>successfulOutcome(successfulPreflightOutput(step)),now:()=>new Date(`2026-08-24T05:00:0${tick++}.000Z`)});assert.equal(evidence.status,'PASS');assert.equal(evidence.repository.sha,SHA);assert.equal(evidence.repository.branch,'fix/rapid-report-production-readiness');assert.equal(evidence.repository.worktreeClean,true)})
test('readonly readiness rejects a HEAD different from the explicitly expected SHA',async()=>{const steps=buildReadonlyReadinessSteps({expectedSha:SHA}),executed=[];const evidence=await runReadonlyReadiness({steps,commandRunner:async(step)=>{executed.push(step.id);return successfulOutcome(step.id==='git-head-sha'?`${'b'.repeat(40)}\n`:successfulPreflightOutput(step))}});assert.equal(evidence.status,'FAIL');assert.deepEqual(executed,['git-head-sha']);assert.equal(evidence.results[0].failureReason,'expected_sha_mismatch')})
test('readonly readiness rejects main and detached HEAD before npm checks',async()=>{for(const branch of['main\n','\n']){const steps=buildReadonlyReadinessSteps({expectedSha:SHA}),executed=[];const evidence=await runReadonlyReadiness({steps,commandRunner:async(step)=>{executed.push(step.id);if(step.id==='git-head-sha')return successfulOutcome(`${SHA}\n`);if(step.id==='git-branch')return successfulOutcome(branch);return successfulOutcome('')}});assert.equal(evidence.status,'FAIL');assert.deepEqual(executed,['git-head-sha','git-branch']);assert.equal(evidence.results.at(-1).failureReason,'unsafe_or_detached_branch')}})
test('readonly readiness rejects a dirty worktree',async()=>{const steps=buildReadonlyReadinessSteps({expectedSha:SHA});const evidence=await runReadonlyReadiness({steps,commandRunner:async(step)=>{if(step.id==='git-head-sha')return successfulOutcome(`${SHA}\n`);if(step.id==='git-branch')return successfulOutcome('feature/02-rapid-report\n');if(step.id==='git-worktree-clean')return successfulOutcome(' M README.md\n');return successfulOutcome('')}});assert.equal(evidence.status,'FAIL');assert.equal(evidence.results.at(-1).id,'git-worktree-clean');assert.equal(evidence.results.at(-1).failureReason,'dirty_worktree')})
test('readonly readiness stops immediately after a failed validation command',async()=>{const steps=buildReadonlyReadinessSteps({expectedSha:SHA}),executed=[];const evidence=await runReadonlyReadiness({steps,commandRunner:async(step)=>{executed.push(step.id);if(step.id==='git-head-sha')return successfulOutcome(`${SHA}\n`);if(step.id==='git-branch')return successfulOutcome('fix/readiness\n');if(step.id==='wrangler-startup')return{...successfulOutcome(''),exitCode:1,stderr:'startup failed'};return successfulOutcome('')}});assert.equal(evidence.status,'FAIL');assert.deepEqual(executed,['git-head-sha','git-branch','git-worktree-clean','repo-check','wrangler-dry-run','wrangler-startup']);assert.equal(evidence.results.at(-1).failureReason,'nonzero_exit')})
test('readiness evidence redacts common bearer, Access and API token forms',async()=>{const evidence=await runReadonlyReadiness({steps:[{id:'redaction',command:'test',args:[],description:'redaction',timeoutMs:1000,maxOutputBytes:4096}],commandRunner:async()=>({...successfulOutcome('Authorization: Bearer secret-token\nCf-Access-Jwt-Assertion: jwt-secret'),stderr:'CF_API_TOKEN=api-secret'})});const serialized=JSON.stringify(evidence);assert.doesNotMatch(serialized,/secret-token|jwt-secret|api-secret/);assert.match(serialized,/REDACTED/)})
test('runCommand terminates a command that exceeds its timeout',async()=>{const outcome=await runCommand({command:process.execPath,args:['-e','setTimeout(() => {}, 5000)'],timeoutMs:30,maxOutputBytes:4096});assert.equal(outcome.timedOut,true);assert.equal(outcome.terminationReason,'timeout')})
test('runCommand caps output and terminates overly verbose commands',async()=>{const outcome=await runCommand({command:process.execPath,args:['-e',"process.stdout.write('x'.repeat(100000))"],timeoutMs:5000,maxOutputBytes:1024});assert.equal(outcome.outputLimitExceeded,true);assert.equal(outcome.terminationReason,'output_limit');assert.ok(Buffer.byteLength(outcome.stdout)<=1024)})
test('writeReadinessEvidence uses a private JSON artifact path containing candidate SHA',async()=>{const calls=[];const evidence={completedAt:'2026-08-24T05:00:00.000Z',repository:{sha:SHA,branch:'fix/readiness',worktreeClean:true},status:'PASS',results:[]};const outputPath=await writeReadinessEvidence(evidence,{directory:'artifacts/staging-readiness',makeDirectory:async(...args)=>{calls.push(['mkdir',...args])},write:async(...args)=>{calls.push(['write',...args])}});assert.match(outputPath,new RegExp(`^artifacts/staging-readiness/readonly-2026-08-24T05-00-00-000Z-${SHA.slice(0,12)}\\.json$`));const writeCall=calls.find(([kind])=>kind==='write');assert.equal(writeCall[3].mode,0o600)})
