import assert from 'node:assert/strict'
import test from 'node:test'
import { EXPECTED_STAGING } from './staging-constants.mjs'
import { LOAD_PROFILES, resolveLoadPlan, runControlledLoad } from './staging-controlled-load.mjs'
function uuidFactory(){let sequence=0;return()=>{sequence+=1;return`00000000-0000-4000-8000-${String(sequence).padStart(12,'0')}`}}
function acceptedResponse(eventId){return new Response(JSON.stringify({event_id:eventId,status:'unverified',verified:false}),{status:202,headers:{'content-type':'application/json'}})}
test('load profiles are intentionally small and bounded',()=>{assert.deepEqual(LOAD_PROFILES['rate-limit'],{requests:15,concurrency:1,sharedClient:true});assert.deepEqual(LOAD_PROFILES.burst,{requests:20,concurrency:4,sharedClient:false});assert.equal(resolveLoadPlan({profile:'rate-limit'}).maxPersistentReports,15);assert.equal(resolveLoadPlan({profile:'burst'}).maxPersistentReports,20)})
test('load plan rejects unsafe request and concurrency values',()=>{for(const requests of[0,26,1.5,Number.NaN])assert.throws(()=>resolveLoadPlan({requests}),/requests must be/);for(const concurrency of[0,5,1.5,Number.NaN])assert.throws(()=>resolveLoadPlan({concurrency}),/concurrency must be/);assert.throws(()=>resolveLoadPlan({profile:'rate-limit',concurrency:2}),/requires concurrency=1/);assert.throws(()=>resolveLoadPlan({profile:'unknown'}),/Unknown load profile/)})
test('controlled load refuses non-staging targets before fetching',async()=>{let called=false;await assert.rejects(runControlledLoad({baseUrl:'https://example.com',fetchImpl:async()=>{called=true;return acceptedResponse('x')}}),/authorized staging Worker/);assert.equal(called,false)})
test('rate-limit profile reuses one synthetic client and records 202/429 evidence',async()=>{const ids=uuidFactory();const calls=[];const fetchImpl=async(url,init)=>{calls.push({url,init});const body=JSON.parse(init.body);if(calls.length<=3)return acceptedResponse(body.event_id);return new Response(JSON.stringify({error:'rate_limited'}),{status:429,headers:{'content-type':'application/json'}})};const outcome=await runControlledLoad({fetchImpl,profile:'rate-limit',requests:5,idFactory:ids,now:()=> '2026-08-24T05:00:00.000Z'});assert.equal(calls.length,5);assert.equal(new Set(calls.map(({init})=>init.headers['X-Client-Id'])).size,1);assert.ok(calls.every(({url})=>url===`${EXPECTED_STAGING.workerUrl}/v1/reports`));assert.equal(outcome.acceptedCount,3);assert.equal(outcome.rateLimitedCount,2);assert.equal(outcome.unexpectedCount,0);assert.equal(outcome.eventIds.length,3)})
test('burst profile uses distinct synthetic clients',async()=>{const ids=uuidFactory();const calls=[];const fetchImpl=async(url,init)=>{calls.push({url,init});const body=JSON.parse(init.body);return acceptedResponse(body.event_id)};const outcome=await runControlledLoad({fetchImpl,profile:'burst',requests:4,concurrency:2,idFactory:ids,now:()=> '2026-08-24T05:00:00.000Z'});assert.equal(new Set(calls.map(({init})=>init.headers['X-Client-Id'])).size,4);assert.equal(outcome.acceptedCount,4);assert.equal(outcome.unexpectedCount,0)})
test('controlled load surfaces unexpected response contracts',async()=>{const outcome=await runControlledLoad({fetchImpl:async()=>new Response(JSON.stringify({error:'storage_unavailable'}),{status:503}),profile:'burst',requests:1,concurrency:1,idFactory:uuidFactory()});assert.equal(outcome.unexpectedCount,1);assert.deepEqual(outcome.statusCounts,{503:1})})
